apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twingate
  namespace: twingate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: twingate
    creationPolicy:  Owner
  data:
    - secretKey: access-token
      remoteRef:
        key: twingate
        property: access-token
    - secretKey: refresh-token
      remoteRef:
        key: twingate
        property: refresh-token
    - secretKey: dns
      remoteRef:
        key: twingate
        property: dns